server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie  # Update with your MySQL DB URL
    username: root  # Replace with your MySQL username
    password: Varun@0502  # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # `update` keeps schema updated, `create-drop` will drop and recreate each time
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Use MySQL dialect
